services:
  - type: web
    name: my-app
    runtime: python # Change this based on your stack
    repo: https://github.com/Stuti0711/Digiflex-Chatbot.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Modify for your framework
    envVars:
      - key: GEMINI_API_KEY
        value: 5000
      - key: 123
        sync: false  # Set to true if using Render's environment variables